#!/usr/bin/env bash
# Configure a custom 404 page

apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error_page
sed -i "/server_name _;/a error_page 404 \/error_page;\nlocation = /error_page {\nroot \/var\/www\/html;\ninternal;\n}" /etc/nginx/sites-available/default
service nginx restart
