#!/usr/bin/env bash
# Configure a custom 404 page

echo "Ceci n'est pas une page" > /var/www/html/error_page
sed -i "/server_name _;/a error_page 404 \/error_page;\nlocation = /error_page {\nroot \/var\/www\/html;\ninternal;\n}" /etc/nginx/sites-available/default
service nginx restart
