#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get -y update
apt-get -y install haproxy
echo "4413-lb-01 54.197.165.111
3.84.111.8 4413-web-01
3.80.41.217 4413-web-02" >> /etc/hosts
echo 'frontend web-frontend
  listen 4413-lb-01   
  bind *:80
  default_backend web-backend

backend web-backend
  balance roundrobin
  server 4413-web-01 3.84.111.8:80 check
  server 4413-web-02 3.80.41.217:80 check
' >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
