#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a
# SIGQUIT or SIGTERM signal
pgrep -f 100-process_and_pid_file >> /var/run/myscript.pid
handle_sigterm() {
    echo "I hate the kill command"
    rm "/var/run/myscript.pid"
    exit
}

handle_sigint() {
    echo "Y U no love me?!"
}

trap handle_sigterm SIGTERM;
trap handle_sigint SIGINT;
trap rm "/var/run/myscript.pid" SIGQUIT;

while true; do
    echo "To infinity and beyond"
    sleep 2
    done
