#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process

start() {
    echo "manage_my_process started"
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
}

stop() {
    echo "manage_my_process stopped"
    rm "/var/run/my_process.pid"
    pkill manage_my_process
}

restart() {
    echo "manage_my_process restarted"
    pkill manage_my_process
    rm "/var/run/my_process.pid"
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
esac

exit 0
