#!/usr/bin/env bash
# script that displays the PID, along with the process name,
# of processes whose name contain the word bash
#
# shellcheck disable=SC2009
pgrep bash | while read -r line ; do
    echo "$line bash"
    done
