#!/usr/bin/env bash
# script that displays the PID, along with the process name,
# of processes whose name contain the word bash
#
# shellcheck disable=SC2009
while true; do
    echo "To infinity and beyond"
    sleep 2
    done
