#!/usr/bin/env bash
# displays:
#    The content of the current directory
#    In a list format
#    Where only the part of the name after the first dash is displayed
FILES="*"
for f in $FILES
do
#    sed -n -e 's/^.*-: //p'
    echo "${f#*-}"
done
