#!/usr/bin/env bash
# Bash script that configures the container

pkill apache2
chmod 666 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
